jobs:
  lint_package_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm lint:package-json

name: Lint Package JSON

on:
  pull_request: ~
  push:
    branches:
      - main
